openapi: 3.0.1

info:
  title: Datasets2Tools
  description: | 
    Datasets2Tools is a platform for the discovery and evaluation of biomedical 
    digital objects. It indexes over 30,000 bioinformatics analyses, over 6,000 
    biological datasets and over 4,000 computational tools. These include a wide
    variety of enrichment analyses; gene interaction networks; interactive data 
    visualizations; and datasets and computational tools spanning technologies 
    such as microarray, RNA-seq, proteomics and many others.
  termsOfService: http://amp.pharm.mssm.edu/datasets2tools/help
  contact: 
    name: Ma'ayan Lab
    url: http://labs.icahn.mssm.edu/maayanlab/contact/
    email: avi.maayan@mssm.edu
    x-role: responsible organization
    x-id: http://labs.icahn.mssm.edu/maayanlab/
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html 
  
tags: 
- name: Maayanlab
- name: NIHdatacommons
  
servers: 
- url: http://amp.pharm.mssm.edu/datasets2tools
  
paths: 
  /api/search: 
    get: 
      operationId: search
      summary: Search a canned analysis, dataset, or tool
      parameters: 
      - name: object_type
        description: Type of object to be searched
        in: query
        schema: 
          type: string
          enum: 
          - canned_analysis
          - dataset
          - tool
          default: canned_analysis
      - name: q
        description: Search all canned analyses, datasets, or tools that contain this keyword
        in: query
        allowReserved: true
        schema: 
          type: string
        example: prostate cancer
      - name: dataset_accession
        description: Search this dataset, or search for canned analyses or tools associated with this dataset
        in: query
        schema: 
          type: string
        example: GSE775
      - name: canned_analysis_accession
        description: Search all datasets or tools used to generate this canned analysis
        in: query
        schema: 
          type: string
        example: DCA00000002
      - name: tool_name
        description: Search this tool, or search for canned analyses or datasets generated by this tool
        in: query
        schema: 
          type: string
        example: Enrichr  
      - name: page_size
        description: Number of search results to display
        in: query
        schema: 
          type: integer
          default: 10
      responses: 
        '200': 
          description: Successful response
          content: 
            application/json: 
              schema: 
                type: array
                items: 
                  type: object
        '400':
          description: Bad request - one or more search parameters invalid
        '404':
          description: Page not found
        '500': 
          description: Unexpected error

x-externalResources:
- x-url: https://github.com/MaayanLab/smartAPIs/blob/master/datasets2tools_smartapi.yml
  x-type: api documentation
- x-url: https://www.nature.com/articles/sdata201823
  x-type: publication
  x-description: | 
    Datasets2Tools, repository and search engine for bioinformatics datasets, 
    tools and canned analyses
